Use Plantsmartvictoria;
DROP TABLE PLANT_SOIL_TEX;
DROP TABLE SOIL_TEXTURE;
DROP TABLE PLANT_FLOWER;
DROP TABLE FLOWER_TIME;
DROP TABLE PLANT_FLO_COLOR;
DROP TABLE FLOWER_COLOR;
DROP TABLE PLANT_INFO;
DROP TABLE PLANT_TYPE;
DROP TABLE FROST;
DROP TABLE SOIL_PH;
DROP TABLE PLANT_GENUS;

CREATE TABLE PLANT_INFO (
	plantid int NOT NULL,
    tube_colour varchar(255),
    botanical_name varchar(255),
    common_name varchar(255),
    height_m varchar(255),
    spread_m varchar(255),
    rain_mm varchar(255),
    plant_type varchar(255),
    plant_genus varchar(255),
    soil_ph varchar(255),
    frost_type varchar(255)
    );    
    
CREATE TABLE PLANT_TYPE(
	plant_type varchar(255) NOT NULL,
	description varchar(255)
);


CREATE TABLE PLANT_GENUS(
	plant_genus varchar(255) NOT NULL,
	description varchar(255)
);

CREATE TABLE FROST(
	frost_type varchar(255) NOT NULL,
    description varchar(255)
);

CREATE TABLE SOIL_TEXTURE(
	soil_type varchar(255) NOT NULL,
	description varchar(255)
);


CREATE TABLE PLANT_SOIL_TEX (
	plantid int Not NULL,
    soil_type varchar(255) NOT NULL
);


CREATE TABLE SOIL_PH(
	soil_ph varchar(255) NOT NULL,
    description varchar(255)
);
CREATE TABLE FLOWER_COLOR(
	flower_color varchar(255) NOT NULL,
	description varchar(255)
);


CREATE TABLE PLANT_FLO_COLOR(
	plantid int NOT NULL,
    flower_color varchar(255) NOT NULL
);

CREATE TABLE FLOWER_TIME(
	flower_time varchar(255) NOT NULL,
	description varchar(255)
);

CREATE TABLE PLANT_FLOWER(
	PLANTID int NOT NULL,
    flower_time varchar(255) NOT NULL
);
ALTER TABLE PLANT_FLOWER ADD CONSTRAINT PLANT_FLOWER_PK PRIMARY KEY (plantid, flower_time);
ALTER TABLE SOIL_PH ADD CONSTRAINT SOIL_PH_PK PRIMARY KEY (soil_ph);
ALTER TABLE PLANT_INFO ADD CONSTRAINT PLANT_INFO_PK PRIMARY KEY (plantid);
ALTER TABLE PLANT_TYPE ADD CONSTRAINT PLANT_TYPE_PK PRIMARY KEY (plant_type);
ALTER TABLE PLANT_GENUS ADD CONSTRAINT PLANT_GENUS_PK PRIMARY KEY (plant_genus);
ALTER TABLE FROST ADD CONSTRAINT FROST_PK PRIMARY KEY (frost_type);
ALTER TABLE SOIL_TEXTURE ADD CONSTRAINT SOIL_TEXTURE_PK PRIMARY KEY (soil_type);
ALTER TABLE PLANT_SOIL_TEX ADD CONSTRAINT PLANT_SOIL_TEX_PK PRIMARY KEY (plantid, soil_type);
ALTER TABLE FLOWER_COLOR ADD CONSTRAINT FLOWER_COLOR_PK PRIMARY KEY (flower_color);
ALTER TABLE PLANT_FLO_COLOR ADD CONSTRAINT PLANT_FLO_COLOR_PK PRIMARY KEY (plantid, flower_color);
ALTER TABLE FLOWER_TIME ADD CONSTRAINT FLOWER_TIME_PK PRIMARY KEY (flower_time);
ALTER TABLE PLANT_SOIL_TEX ADD CONSTRAINT PLANT_SOIL_PL_FK FOREIGN KEY (plantid) REFERENCES PLANT_INFO(plantid);
ALTER TABLE PLANT_SOIL_TEX ADD CONSTRAINT PLANT_SOIL_TEX_FK FOREIGN KEY (soil_type) REFERENCES SOIL_TEXTURE(soil_type);
ALTER TABLE PLANT_FLO_COLOR ADD CONSTRAINT PLANT_FLO_PL_FK FOREIGN KEY (plantid) REFERENCES PLANT_INFO(plantid);
ALTER TABLE PLANT_FLO_COLOR ADD CONSTRAINT PLANT_FLO_CO_FK FOREIGN KEY (flower_color) REFERENCES FLOWER_COLOR(flower_color);
ALTER TABLE PLANT_FLOWER ADD CONSTRAINT PLANT_FLOW_PL_FK FOREIGN KEY (plantid) REFERENCES PLANT_INFO(plantid);
ALTER TABLE PLANT_FLOWER ADD CONSTRAINT PLANT_FLOW_TI_FK FOREIGN KEY (flower_time) REFERENCES FLOWER_TIME(flower_time);
ALTER TABLE PLANT_INFO ADD CONSTRAINT PLANT_INFO_TYPE_FK FOREIGN KEY (plant_type) REFERENCES PLANT_TYPE(plant_type);
ALTER TABLE PLANT_INFO ADD CONSTRAINT PLANT_INFO_GENUS_FK FOREIGN KEY (plant_genus) REFERENCES PLANT_GENUS(plant_genus);
ALTER TABLE PLANT_INFO ADD CONSTRAINT PLANT_INFO_PH_FK FOREIGN KEY (soil_ph) REFERENCES SOIL_PH(soil_ph);
ALTER TABLE PLANT_INFO ADD CONSTRAINT PLANT_INFO_FROST_FK FOREIGN KEY (frost_type) REFERENCES FROST(frost_type);
